### ISSUE TITLE
When using Docker, an error is reported during upload

### ISSUE THREAD

**Issue by t880216t** [sitespeedio/onlinetest#11]
```yaml
    - name: "Desktop Browsers"
      type: "desktop"
      # If you do not use Docker, you need to make sure you
      # install the browsers yourself
      browsers: [ "chrome", "firefox", "edge" ]
      connectivity: [ "native", "3g", "4g", "cable" ]
      # If you choose to run sitespeed.io docker containers make sure
      # to run: sudo modprobe ifb numifbs=1
      # on the host so that setting connectivity will work
      useDocker: true
```

result log:

```text
[2024-06-04 07:54:23] ERROR: Could not upload to S3 UnknownEndpoint: Inaccessible host: `sitespeedio.127.0.0.1' at port `undefined'. This service may not be available in the `us-east-1' region. at Request.ENOTFOUND_ERROR (/usr/src/app/node_modules/aws-sdk/lib/event_listeners.js:612:46) at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/request.js:686:14) at error (/usr/src/app/node_modules/aws-sdk/lib/event_listeners.js:443:22) at ClientRequest.(/usr/src/app/node_modules/aws-sdk/lib/http/node.js:100:9) at ClientRequest.emit (node:events:514:28) at ClientRequest.emit (node:domain:488:12) at Socket.socketErrorListener (node:_http_client:495:9) at Socket.emit (node:events:514:28) at Socket.emit (node:domain:488:12) at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
