### ISSUE TITLE
Enable lighthouse plugin and run failed

### ISSUE THREAD

**Issue by altmangood** [sitespeedio/onlinetest#116]
### error info
> Job failed:Command failed with ENOENT: sitespeed.io --config /tmp/default/1793d987-095f-4814-9009-54cc2f96a434/default-1793d987-095f-4814-9009-54cc2f96a434-config.json --storeResult /tmp/default/1793d987-095f-4814-9009-54cc2f96a434/default-1793d987-095f-4814-9009-54cc2f96a434-result.json --disableAPI true 'https://www.example.com' spawn sitespeed.io ENOENT

<img width="1039" alt="image" src="https://github.com/user-attachments/assets/cb407f51-0a94-48ad-a263-95d5fb46108a" />

### docker config

runner default.yaml (just show updated section)
```
docker:
  container: "sitespeedio/sitespeed.io:35.7.5-plus1"
  extraparameters: "--cap-add=NET_ADMIN"
  #baselinedir: "$(pwd)"
```

server default.yaml (just show updated section)
```
## Configure the GUI
html:
  css:
    override:
  logo:
    path: "/img/logo.svg"
    width: 300
    alt: "sitespeed.io logo"
  logoHeader:
    path: "/img/logoHeader.svg"
    width: 112
    height: 18
    alt: "sitespeed.io logo"
  ## Setup a folder that will be mapped to /extras - use this of you want to change 
  ## the current look and feel
  extras:
    path:
  # You can choose to either show the log from sitespeed.io or a random AI generated image.
  showRandomAIImage: false
  # Show the Lighthouse box
  useLighthouse: true
```

compose.app.yaml (just modify volumes, because need mapping local yaml config to docker)

```
services:
  sitespeed.io-server:
    image: sitespeedio/server:${SITESPEED_IO_SERVER_VERSION}
    environment:
      redis_host: keydb
      redis_port: 6379
      redis_password: ${KEYDB_PASSWORD}
      database_user: ${POSTGRES_USER}
      database_server: postgresql
      database_name: sitespeedio
      database_password: ${POSTGRES_PASSWORD}
      database_port: 5432
      validTestDomains: ${VALID_TEST_DOMAINS}
    ports:
      - "3000:3000"
    networks:
      - skynet
    depends_on:
      - keydb
      - postgresql
      - minio
    volumes:
      - ./config/server/default.yaml:/usr/src/app/config/default.yaml
  sitespeed.io-testrunner:
    image: sitespeedio/testrunner:${SITESPEED_IO_TESTRUNNER_VERSION}
    environment:
      redis_host: keydb
      redis_port: 6379
      redis_password: ${KEYDB_PASSWORD}
      location_name: ${LOCATION_NAME}
      docker_container: ${SITESPEED_IO_CONTAINER}
      docker_extraparameters: '--cap-add=NET_ADMIN --network=skynet'
      sitespeed.io_s3_endpoint: "http://minio:9000" 
      sitespeed.io_s3_bucketname: 'sitespeedio'
      sitespeed.io_s3_key: ${MINIO_USER}
      sitespeed.io_s3_secret:  ${MINIO_PASSWORD}
      sitespeed.io_s3_region: "motown"
      sitespeed.io_s3_options_forcePathStyle: true
      sitespeed.io_s3_removeLocalResult: true
      sitespeed.io_resultBaseURL: ${RESULT_BASE_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - ./config/runner/default.yaml:/usr/src/app/config/default.yaml
    cap_add:
      - NET_ADMIN
    depends_on:
      - keydb
      - minio
      - sitespeed.io-server
    networks:
      - skynet

```
